### ISSUE TITLE
Rethinking output format

### ISSUE THREAD

**Issue by kjschiroo** [kjschiroo/WikiChatter#15]
I'm not really happy with the current output format. It is the way it is because it was convenient based on the implementation, and not because it was really the best choice for the end user. My current plan is to convert to output that is composed of strictly lists, dictionaries, and strings. There would be four concepts to deal with: pages, sections, comments, and textblocks. 
#### Page

```
{
    'page_title': <page_title>
    'sections': [ Sections ]
}
```
#### Section

```
{
    'section_title': <section_title>,
    'author': <author_username>,
    'time_stamp': <time_stamp>,
    'comments': [ Comments ],
    'subsections' [ Sections ]
}
```
#### Comment

```
{
    'author': <author_username>,
    'time_stamp': <time_stamp>,
    'text_blocks': [ TextBlocks ]
}
```
#### TextBlock

```
{
    'text': <text>,
    'comments': [ Comments ]
}
```
#### Example

```
Page
  Section
    Comment
      TextBlock
        Comment
          TextBlock
          TextBlock
      TextBlock
  Section
    Comment
      TextBlock
    Section
      Comment
        TextBlock
      Comment
        TextBlock
```

I think that this format would allow for everything that I have seen so far to be expressed and would make sense regardless of implementation details. It would allow for arbitrary subsections and would be able to keep track of responses that are nested within someone's comment (I usually only see this when someone is responding to a bullet point in a list). 

I've spoken briefly with @halfak regarding this and would also like to get @yuvipanda's thoughts.

**Comment by yuvipanda** [comment]
This looks nice to me. I would suggest writing a JSON Schema for this first, and then a bunch of us can look at it and review it to spot problems and then implementing it.

**Comment by kjschiroo** [comment]
Neat, I'd never heard about JSON Schema before. I've included the schema that I am proposing below.

```
{
    "$schema": "http://json-schema.org/draft-04/schema#",

    "definitions": {
        "page":{
            "type": "object",
            "properties": {
                "title": {"type": "string"},
                "sections": {
                    "type": "array",
                    "items": {"$ref": "#/definitions/section"}
                }
            }
        },
        "section": {
            "type": "object",
            "properties": {
                "section_title": {"type": "string"},
                "comments":{
                    "type": "array",
                    "items": {"$ref": "#/definitions/comment"}
                },
                "subsections": {
                    "type": "array",
                    "items": {"$ref": "#/definitions/section"}
                }
            }
        },
        "comment": {
            "type": "object",
            "properties": {
                "author": {"type": "string"},
                "time_stamp": {"$ref": "#/definitions/time_stamp"},
                "text_blocks": {
                    "type": "array",
                    "items": {"$ref": "#/definitions/text_block"}
                }
            }
        },
        "text_block": {
            "type": "object",
            "properties": {
                "text": {"type": "string"},
                "comments": {
                    "type": "array",
                    "items": {"$ref": "#/definitions/comment"}
                }
            }
        },
        "time_stamp": {
            "type": "string",
            "pattern": "[0-9]{2}:[0-9]{2}, [0-9]{1,2} [a-zA-Z]+ [0-9]{4} \\(UTC\\)"
        }
    },

    "$ref": "#/definitions/page"
}
```

Edit: Removed author and time_stamp from section

**Comment by yuvipanda** [comment]
awesome! I think time_stamp should be ISO8601 format. Also I think comments should have the nested comments property, rather than text blocks. That way text blocks only refer to the text blocks of the current comment.

**Comment by kjschiroo** [comment]
@yuvipanda Could you elaborate on what you mean regarding 

> text blocks only refer to the text blocks of the current comment.

As I understand your message there wouldn't appear to be a place for text blocks, instead there would only be comments. I'm assuming I am misunderstanding.
