### ISSUE TITLE
Include markup retrieval in examples

### ISSUE THREAD

**Issue by Ironholds** [kjschiroo/WikiChatter#21]
The examples all assume that the data has already been retrieved, and don't give many hints as to how to get it or what form it takes. It would be good if they included an example of grabbing the markup from MediaWiki.

**Comment by kjschiroo** [comment]
My initial thought on this is that markup collection is out of the scope of the module.

If you are suggesting putting forward a potential separate module for the user to use in conjunction with this one to do the actual collection I would be interested in hearing @yuvipanda's or @halfak's thoughts as to the most straightforward method of collection.

**Comment by yuvipanda** [comment]
I agree that adding it into the module seems out of scope. we should
definitely include examples, possibly using the python-mwapi module, on
using it to retrieve markup and this to parse it.

**Comment by Ironholds** [comment]
Yeah, for reference I mean example.py or even the README, not incorporating markup retrieval into the module - although the inline docs providing some pointers could be nice.
